# Generated by Django 5.2.17 on 2026-10-04 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('denied', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
                ('photo_link', models.URLField(default='http://localhost/default.jpg')),
                ('linked_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='linked_manager', to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('meetingID', models.CharField(default='', max_length=20)),
                ('welcome', models.CharField(default='خوش آمدید.', max_length=1000)),
                ('duration', models.IntegerField(default=0)),
                ('moderatorPW', models.CharField(default='m0D3R@1oR', max_length=10)),
                ('attendeePW', models.CharField(default='@tT3nd33', max_length=10)),
                ('record', models.BooleanField(default=True)),
                ('autoStartRecording', models.BooleanField(default=True)),
                ('webcamsOnlyForModerator', models.BooleanField(default=True)),
                ('maxParticipants', models.IntegerField(default=0)),
                ('allowStartStopRecording', models.BooleanField(default=True)),
                ('slides', models.TextField(default='localhost/whiteboard.pdf\n')),
                ('selected_slides', models.TextField(default='localhost/whiteboard.pdf\n')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_arena.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ManyToManyField(to='study_arena.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=8)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_arena.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_arena.student')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.ManyToManyField(to='study_arena.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=8)),
                ('clazz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_arena.class')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_arena.teacher')),
            ],
        ),
    ]
